apiVersion: v1
kind: Service
metadata:
  name: {{ template "jaeger.fullname" . }}-query
  labels:
    app: {{ template "jaeger.name" . }}
    chart: {{ template "jaeger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: jaeger
spec:
  type: {{ .Values.service.query.type }}
  selector:
    app: {{ template "jaeger.name" . }}
    release: {{ .Release.Name }}
    component: jaeger
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
