apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "jaeger.fullname" . }}
  labels:
    app: {{ template "jaeger.name" . }}
    chart: {{ template "jaeger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: jaeger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "jaeger.name" . }}
      release: {{ .Release.Name }}
      component: jaeger
  template:
    metadata:
      labels:
        app: {{ template "jaeger.name" . }}
        release: {{ .Release.Name }}
        component: jaeger
    spec:
      containers:
      - name: jaeger
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- range $key, $val := .Values.config.env }}
          - name: {{ $key | quote}}
            value: {{ $val | quote }}
        {{- end }}
        args:
          - "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"
        {{- range .Values.config.args }}
          - {{ . | quote }}
        {{- end }}
        ports:
          - containerPort: 6831
            protocol: UDP
          - containerPort: 16686
            protocol: TCP
        readinessProbe:
          httpGet:
            path: "/"
            port: 14269
          initialDelaySeconds: 5
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
