language: generic

dist: trusty
sudo: false

services:
- docker

script:
- make lint

before_deploy:
- |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/id_rsa)"

    openssl aes-256-cbc \
      -K $encrypted_12c8071d2874_key \
      -iv $encrypted_12c8071d2874_iv \
      -in ".travis/github_deploy_key.enc" \
      -out "$SSH_FILE" -d

    chmod 600 "$SSH_FILE" \
    && printf "%s\n" \
          "Host github.com" \
          "  IdentityFile $SSH_FILE" \
          "  LogLevel ERROR" >> ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: make publish
  on:
    branch: master
