{{- if .Values.ethstats.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geth.fullname" . }}-ethstats
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  WS_SECRET: {{ .Values.ethstats.webSocketSecret | b64enc | quote }}
{{- end }}
