{{- if .Values.ethstats.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "geth.fullname" . }}-ethstats
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: ethstats
spec:
  selector:
    app: {{ template "geth.name" . }}
    release: {{ .Release.Name }}
    component: ethstats
  type: {{ .Values.ethstats.service.type }}
  ports:
  - port: 80
    targetPort: http
{{- end }}
