kind: Service
apiVersion: v1
metadata:
  name: {{ template "geth.fullname" . }}-geth
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: geth
spec:
  selector:
    app: {{ template "geth.name" . }}
    release: {{ .Release.Name }}
    component: geth
  type: {{ .Values.geth.service.type }}
  sessionAffinity: ClientIP
  ports:
  - name: rpc
    port: 8545
  {{- if .Values.geth.config.ws }}
  - name: ws
    port: 8546
  {{- end }}
