dependencies:
  # Metrics
  - name: "influxdb"
    version: 0.11.0
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kapacitor"
    version: 1.1.1
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kapacitor-importer"
    version: 0.0.1
    condition: swarm.metricsEnabled
    repository: https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/
  - name: "grafana"
    version: 1.14.8
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/

  # Tracing
  - name: "jaeger"
    version: 0.0.3
    condition: swarm.tracingEnabled
    repository: https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/
