{{- $root := . -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "smoke.fullname" $root }}-smoke
  labels:
    app: {{ template "smoke.name" $root }}
    chart: {{ template "smoke.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ $root.Values.smoke.schedule }}"
  successfulJobsHistoryLimit: {{ $root.Values.smoke.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $root.Values.smoke.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ $root.Values.smoke.concurrencyPolicy | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: smoke
            image: {{ .Values.smoke.image.repository }}:{{ .Values.smoke.image.tag }}
            imagePullPolicy: {{ .Values.smoke.imagePullPolicy | quote }}
            command: ["/run-smoke.sh"]
            resources:
{{ toYaml .Values.smoke.resources | indent 14 }}
            args:
            - --cluster-endpoint={{ $root.Release.Namespace }}
            - --app={{ .Values.smoke.config.target }}
            - --cluster-from=0
            - --cluster-to={{ .Values.smoke.config.swarmReplicas }}
            - --cluster-scheme=http
            - --filesize={{ .Values.smoke.config.filesize }}
            - --single
            - --sync-delay={{ .Values.smoke.config.syncdelay }}
            - --verbosity=5
            - --metrics
            - --metrics.influxdb.endpoint=http://{{ .Values.smoke.config.influxdbReleaseName }}.{{ $root.Release.Namespace }}:8086
            - --metrics.influxdb.username={{ .Values.smoke.config.influxdbUsername }}
            - --metrics.influxdb.password={{ .Values.smoke.config.influxdbPassword }}
            - --metrics.influxdb.database=metrics
            - --metrics.influxdb.host.tag=single-{{ .Values.smoke.config.syncdelay }}-{{ .Values.smoke.config.filesize }}
            - c
          restartPolicy: Never
