apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "swarm.fullname" . }}-bootnode
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: bootnode
spec:
  serviceName: {{ template "swarm.fullname" . }}-bootnode
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "swarm.name" . }}
      release: {{ .Release.Name }}
      component: bootnode
  template:
    metadata:
      labels:
        app: {{ template "swarm.name" . }}
        release: {{ .Release.Name }}
        component: bootnode
    {{- if or (eq .Values.bootnode.image.tag "latest") (eq .Values.bootnode.image.tag "edge") }}
      annotations:
        # Note: 'latest' or 'edge' tag is beeing used, therefore we keep changing
        # this annotation to force a redeployment of the pods within the StatefulSet
        "release-timestamp": {{.Release.Time.Seconds | quote }}
    {{- end }}
    spec:
      containers:
      - name: bootnode
        image: {{ .Values.bootnode.image.repository }}:{{ .Values.bootnode.image.tag }}
        imagePullPolicy: {{ .Values.bootnode.imagePullPolicy }}
        resources:
{{ toYaml .Values.bootnode.resources | indent 10 }}
        command:
        - sh
        - -ac
        - >
          /run.sh
          --debug
          --bootnode-mode
          --nodekey=/keys/bootnode.key
          --verbosity={{ .Values.bootnode.config.verbosity }}
          --maxpeers=5000
          --nat=ip:$POD_IP
          --port=30301
          --bzznetworkid={{ .Values.swarm.config.bzznetworkid }}
          # Non-existent bootnode until we have a way to specify that we want empty bootnodes list, see https://github.com/ethereum/go-ethereum/pull/18509
          --bootnodes=enode://1519bbd8251a4f3a0a2aa1f62b08741ded86ca8d4f08ade1fd3447866816ce129f3dae84b8078d2a6a6d41764c2ebb39ec608695fa588912b84025fd514f8ab0@10.255.255.212:33399
{{- range $i, $flag := .Values.bootnode.config.extraFlags }}
          {{ $flag }}
{{- end }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "swarm.fullname" . }}
              key: PASSWORD
        ports:
        - name: network
          containerPort: 30301
        volumeMounts:
        - name: keys
          mountPath: /keys
          readOnly: true
      volumes:
      - name: keys
        secret:
          secretName: {{ template "swarm.fullname" . }}-bootnode
{{- with .Values.bootnode.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.bootnode.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.bootnode.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
