apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "swarm.fullname" . }}
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: swarm

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "swarm.fullname" . }}
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: swarm
rules:
- apiGroups: [""]
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "patch"
  - "update"
  - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "swarm.fullname" . }}
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: swarm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "swarm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "swarm.fullname" . }}
    namespace: {{ .Release.Namespace }}
