apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "swarm.fullname" . }}-scripts
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: swarm
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
